# Generated by Django 3.0.1 on 2020-01-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200127_1143'),
        ('participants', '0002_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
            preserve_default=False,
        ),
    ]
