# Generated by Django 3.0.1 on 2020-01-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='name',
        ),
        migrations.AddField(
            model_name='courses',
            name='detail',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(default=None, upload_to='courses/images'),
        ),
    ]
