# Generated by Django 3.2.4 on 2021-06-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200127_1143'),
        ('courses', '0003_auto_20200124_1259'),
    ]

    operations = [
    ]
